# Generated by Django 3.1.1 on 2020-09-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='', upload_to='blog/static/img'),
        ),
        migrations.AddField(
            model_name='post',
            name='price_2hour',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='price_hour',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='price_night',
            field=models.CharField(default='', max_length=5),
        ),
    ]
