# Generated by Django 3.1.1 on 2020-09-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='/static/img/img.jpg', upload_to='static'),
        ),
    ]
